package javaapplication2;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author damoreanope
 */
public class FrmPPTLS extends javax.swing.JFrame 
{

    int aleatorio;
    public FrmPPTLS() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPiedra = new javax.swing.JButton();
        btnPapel = new javax.swing.JButton();
        btnTijera = new javax.swing.JButton();
        btnLagarto = new javax.swing.JButton();
        btnSpoke = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnPiedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/piedra.PNG"))); // NOI18N
        btnPiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiedraActionPerformed(evt);
            }
        });

        btnPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/papel.PNG"))); // NOI18N
        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btnTijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/tijera.PNG"))); // NOI18N
        btnTijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTijeraActionPerformed(evt);
            }
        });

        btnLagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/lagarto.PNG"))); // NOI18N
        btnLagarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLagartoActionPerformed(evt);
            }
        });

        btnSpoke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/spoke.PNG"))); // NOI18N
        btnSpoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpokeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnPiedra)
                        .addGap(18, 18, 18)
                        .addComponent(btnPapel)
                        .addGap(43, 43, 43)
                        .addComponent(btnTijera))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnLagarto)
                        .addGap(51, 51, 51)
                        .addComponent(btnSpoke)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPapel)
                    .addComponent(btnPiedra)
                    .addComponent(btnTijera))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLagarto)
                    .addComponent(btnSpoke))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        aleatorio = (int)(Math.random()*5+1);
        System.out.print(aleatorio);
    }//GEN-LAST:event_formWindowOpened

    private void btnPiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiedraActionPerformed
        if(aleatorio == 1)
        {
            JOptionPane.showMessageDialog(null,"Empate");
        }
        else if((aleatorio == 2) || (aleatorio == 5))
        {
            JOptionPane.showMessageDialog(null,"Perdiste");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Ganaste");
        }
    }//GEN-LAST:event_btnPiedraActionPerformed

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelActionPerformed
        if(aleatorio == 2)
        {
            JOptionPane.showMessageDialog(null, "Empate");
        }
        else if ((aleatorio == 3) || (aleatorio == 4))
        {
            JOptionPane.showMessageDialog(null, "Perdiste");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Ganaste");
        }
    }//GEN-LAST:event_btnPapelActionPerformed

    private void btnTijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTijeraActionPerformed
        if(aleatorio == 3)
        {
            JOptionPane.showMessageDialog(null, "Ëmpate");
        }
        else if((aleatorio == 1) || (aleatorio == 5))
        {
            JOptionPane.showMessageDialog(null, "Perdiste");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Ganaste");
        }
    }//GEN-LAST:event_btnTijeraActionPerformed

    private void btnLagartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagartoActionPerformed
        if(aleatorio == 4)
        {
            JOptionPane.showMessageDialog(null, "Empate");
        }
        else if((aleatorio == 1)|| (aleatorio == 3))
        {
            JOptionPane.showMessageDialog(null, "Perdiste");
        }        
        else
        {
            JOptionPane.showMessageDialog(null, "Ganaste");
        }
    }//GEN-LAST:event_btnLagartoActionPerformed

    private void btnSpokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpokeActionPerformed
        if(aleatorio == 5)
        {
            JOptionPane.showMessageDialog(null, "Empate");
        }
        else if ((aleatorio == 4)|| (aleatorio == 2))
        {
            JOptionPane.showMessageDialog(null, "Perdiste");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Ganaste");
        }
    }//GEN-LAST:event_btnSpokeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPPTLS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLagarto;
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnPiedra;
    private javax.swing.JButton btnSpoke;
    private javax.swing.JButton btnTijera;
    // End of variables declaration//GEN-END:variables
}
